# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20160216_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='photo',
            field=models.FileField(upload_to='files'),
        ),
    ]
