# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20160216_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='photo',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
