# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='stud',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
    ]
