# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_stud_clss'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=120)),
                ('cfont', models.CharField(max_length=120)),
                ('cfontsize', models.IntegerField()),
                ('addline1', models.CharField(max_length=120)),
                ('addline2', models.CharField(max_length=120)),
                ('addline3', models.CharField(max_length=120)),
                ('addline4', models.CharField(max_length=120)),
                ('addline5', models.CharField(max_length=120)),
                ('addline1to5font', models.CharField(max_length=120)),
                ('addline1to5fontsize', models.IntegerField()),
                ('detfont', models.CharField(max_length=120)),
                ('detfontsize', models.IntegerField()),
                ('clogo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('ilogo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('psign', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('bdesign', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
