# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_fdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='admno',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
